name: Python Syntax Check

on: [push, pull_request]

jobs:
  syntax-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Check Python syntax in /koda/python_scripts
        run: |
          find ./Koda/python_scripts -name "*.py" -print0 | xargs -0 python -m py_compile
